# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build framework with Maven
      run: mvn -B install --file framework/pom.xml
    - name: Build examples with Maven
        run: mvn -B install --file examples/pom.xml -Dmaven.test.skip=true
    - name: Run sonar for framework
      run: mvn -B verify sonar:sonar --file framework/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Run Sonar for examples
      run: mvn -B sonar:sonar --file examples/pom.xml -Dmaven.test.skip=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    ################################
    # Run Linter against code base #
    ################################
    - name: Lint Code Base
      uses: docker://github/super-linter:v2.1.1
      env:
        DEFAULT_BRANCH: main
